### ISSUE TITLE
typescript errors

### ISSUE THREAD

**Issue by nbros** [shyguy1412/esbuild-bitburner-plugin#4]
I'm seeing the following typescript errors with esbuild-bitburner-plugin 1.7.5 in a bb-external-editor project :
```
node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/types/index.d.ts:3:23 - error TS2688: Cannot find type definition file for 'node'.

3 /// <reference types="node" />
                        ~~~~

node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/types/index.d.ts:5:21 - error TS2307: Cannot find module 'fs' or its corresponding type declarations.

5 import * as fs from "fs";
                      ~~~~

node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/types/index.d.ts:6:30 - error TS2307: Cannot find module 'events' or its corresponding type declarations.

6 import { EventEmitter } from "events";
                               ~~~~~~~~

node_modules/.pnpm/esbuild-bitburner-plugin@1.7.5/node_modules/esbuild-bitburner-plugin/build/index.d.ts:5:46 - error TS2304: Cannot find name 'BitburnerPluginOptions'.

5 export declare const BitburnerPlugin: (opts: BitburnerPluginOptions) => Plugin;
                                               ~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/esbuild-bitburner-plugin@1.7.5/node_modules/esbuild-bitburner-plugin/build/lib/RemoteApiServer.d.ts:5:14 - error TS2304: Cannot find name 'BitburnerPluginOptions'.

5     options: BitburnerPluginOptions;
               ~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/esbuild-bitburner-plugin@1.7.5/node_modules/esbuild-bitburner-plugin/build/lib/RemoteApiServer.d.ts:8:26 - error TS2304: Cannot find name 'BitburnerPluginOptions'.

8     constructor(options: BitburnerPluginOptions);
                           ~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/esbuild-bitburner-plugin@1.7.5/node_modules/esbuild-bitburner-plugin/build/lib/RemoteApiServer.d.ts:15:53 - error TS2304: Cannot find name 'BitburnerPluginOptions'.

15     mirror(targetPath: string, servers: NonNullable<BitburnerPluginOptions['mirror']>[string]): Promise<RemoteFileMirror>;
                                                       ~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/esbuild-bitburner-plugin@1.7.5/node_modules/esbuild-bitburner-plugin/build/lib/RemoteApiServer.d.ts:16:52 - error TS2304: Cannot find name 'BitburnerPluginOptions'.

16     distribute(targetPath: string, to: NonNullable<BitburnerPluginOptions['mirror']>[string]): () => void;
                                                      ~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/esbuild-bitburner-plugin@1.7.5/node_modules/esbuild-bitburner-plugin/build/lib/RemoteApiServer.d.ts:58:46 - error TS2304: Cannot find name 'BitburnerPluginOptions'.

58 export declare function setupRemoteApi(opts: BitburnerPluginOptions): RemoteApiServer;
                                                ~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/esbuild-bitburner-plugin@1.7.5/node_modules/esbuild-bitburner-plugin/build/lib/RemoteFileMirror.d.ts:9:24 - error TS2503:
 Cannot find namespace 'NodeJS'.

9     remotePollTimeout: NodeJS.Timeout | undefined;
                         ~~~~~~

node_modules/.pnpm/esbuild-bitburner-plugin@1.7.5/node_modules/esbuild-bitburner-plugin/build/lib/RemoteFileMirror.d.ts:11:14 - error TS2304: Cannot find name 'BitburnerPluginOptions'.

11     options: BitburnerPluginOptions;
                ~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/esbuild-bitburner-plugin@1.7.5/node_modules/esbuild-bitburner-plugin/build/lib/RemoteFileMirror.d.ts:12:60 - error TS2304: Cannot find name 'BitburnerPluginOptions'.

12     static create(targetPath: string, servers: NonNullable<BitburnerPluginOptions['mirror']>[string], options: BitburnerPluginOptions): Promise<RemoteFileMirror>;
                                                              ~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/esbuild-bitburner-plugin@1.7.5/node_modules/esbuild-bitburner-plugin/build/lib/RemoteFileMirror.d.ts:12:112 - error TS2304: Cannot find name 'BitburnerPluginOptions'.

12     static create(targetPath: string, servers: NonNullable<BitburnerPluginOptions['mirror']>[string], options: BitburnerPluginOptions): Promise<RemoteFileMirror>;
                                                                                                                  ~~~~~~~~~~~~~~~~~~~~~~    

node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/types/index.d.ts:3:23 - error TS2688: Cannot find type definition file for 'node'.

3 /// <reference types="node" />
                        ~~~~

node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/types/index.d.ts:5:21 - error TS2307: Cannot find module 'fs' or its corresponding type declarations.

5 import * as fs from "fs";
                      ~~~~

node_modules/.pnpm/chokidar@3.6.0/node_modules/chokidar/types/index.d.ts:6:30 - error TS2307: Cannot find module 'events' or its corresponding type declarations.

6 import { EventEmitter } from "events";
                               ~~~~~~~~

```

**Comment by shyguy1412** [comment]
ye, i fucked up trying to make some times ambient. I assumed TSC would just pick up on that but ig not. Should be fixed with ce74d8d220da39afb79786837e8e885251f9de3a

**Comment by nbros** [comment]
Thanks 👍 
I noticed that VS Code only shows TypeScript errors for files currently open in editors.
This seems to be linked to this issue open since 2016!
https://github.com/microsoft/vscode/issues/13953

**Comment by nbros** [comment]
That fixed most of the errors but I still see these:
![Image](https://github.com/user-attachments/assets/cf493a98-177a-496d-b71c-05eeb88153f7)
I may be doing something wrong?
